# hyperparams, paths (mot_root, video_path, epochs, etc.)

mot_root: /home/kms2069/Projects/yolo_tracking/assets/polyp_test_mot/train
video_path: /home/kms2069/Projects/boxmot/test_04-01_obj2_30s.avi
lstm_weights: lstm_weights.pth
feat_dim: 4
hidden_dim: 128
window_size: 5
batch_size: 32
epochs: 350
learning_rate: 1e-3
device: cuda:0
track_config:
  tracker_type: deepocsort
  with_reid: false
  track_buffer: 60